<?php
require('../includes/common.php');
error_reporting(0);
session_start();
if (!$_SESSION['set']) {
    header('location:../index.php');
}
$msg = ' ';
if (isset($_POST['submit'])) {
    $fname = $_POST['fname'];
    $lname = $_POST['lname'];
    $desig = $_POST['desig'];
    $role = $_POST['role'];
    $office = $_POST['office'];
    $home = $_POST['home'];
    $mailid = $_POST['mailid'];
    $dept = $_POST['Department'];

    $query = "INSERT INTO employee(fname,lname,designation,lid)VALUES('" . $fname . "','" . $lname . "','" . $desig . "','" . $dept . "')";
    $sql = mysqli_query($con, $query) or die(mysqli_error($con));
    $instid = mysqli_insert_id($con); //returns the ID generated by a query on a table with a column having the AUTO_INCREMENT attribute or the value for the last usage of LAST_INSERT_ID(expr).
    //echo $instid;
    $query3 = "INSERT INTO callerid(locationstatus,phone,eid) VALUES('office','" . $office . "','" . $instid . "')";
    //echo $query3;
    $result2 = mysqli_query($con, $query3) or die(mysqli_errno($con));

    $query4 = "INSERT INTO emailid(mailid,eid) VALUES('" . $mailid . "','" . $instid . "')";
    $result3 = mysqli_query($con, $query4) or die(mysqli_errno($con));

    $query6 = "INSERT INTO emprole(eid,lid,role) VALUES('" . $instid . "','" . $dept . "','" . $role . "')";
    echo  $query6;
    $result6 = mysqli_query($con, $query6) or die(mysqli_errno($con));

    if (isset($_POST['home']) && $_POST['home'] == '') {
    } elseif (isset($_POST['home'])) {
        $query5 = "INSERT INTO callerid(locationstatus,phone,eid) VALUES('home','" . $home . "','" . $instid . "')";
        $result5 = mysqli_query($con, $query5)
            or die(mysqli_errno($con));
    }
    $msg = "Added successfully.";
}
?>
<!DOCTYPE html>

<head>
    <title>Admin| Add Users</title>
    <link type="text/css" href="include/bootstrap.min.css" rel="stylesheet">
    <link type="text/css" href="include/bootstrap-responsive.min.css" rel="stylesheet">

    <link type="text/css" href="include/theme.css" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.3.2/css/bootstrap-responsive.min.css">

</head>

<body>
    <div class="wrapper">
        <div class="container">
            <div class="row">
                <?php include('include/sidebar.php'); ?>
                <div class="span9">
                    <div class="content">

                        <div class="module">
                            <div class="module-body">

                                <?php if ($msg) {
                                    printf(htmlentities($msg));
                                } ?>

                                <br />

                                <form class="form-horizontal row-fluid" method="post">

                                    <div class="control-group">
                                        <label class="control-label"><b>First Name</b> </label>
                                        <div class="controls">
                                            <input type="text" placeholder="Enter First Name" name="fname" class="span8 tip" required>
                                        </div>
                                    </div>
                                    <div class="control-group">
                                        <label class="control-label"><b>Last Name</b> </label>
                                        <div class="controls">
                                            <input type="text" placeholder="Enter Last Name" name="lname" class="span8 tip" required>
                                        </div>
                                    </div>
                                    <div class="control-group">
                                        <label class="control-label"><b>Department</b> </label>
                                        <div class="controls">
                                            <select name="Department" id="Department" class="span8 tip" required>
                                                <?php
                                                $queryLo = "SELECT * FROM location";
                                                $resultLo = mysqli_query($con, $queryLo) or die(mysqli_errno($con));
                                                printf("<option selected disabled>Open this select menu</option>");
                                                while ($rowLo = mysqli_fetch_array($resultLo)) {

                                                    printf("<option value=" . $rowLo["lid"] . ">" . $rowLo["description"] . "</option>");
                                                }
                                                ?>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="control-group">
                                        <label class="control-label"><b>Designation</b> </label>
                                        <div class="controls">
                                            <select name="desig" id="desig" class="span8 tip" required>
                                                <option selected disabled>Open this select menu</option>
                                                <option value="HOD">HOD</option>
                                                <option value="professor">Professor</option>
                                                <option value="associate professor">Associate Professor</option>
                                                <option value="assistant professor">Assistant Professor</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="control-group">
                                        <label class="control-label"><b>Role</b> </label>
                                        <div class="controls">
                                            <select name="role" id="role" class="span8 tip">
                                                <option selected disabled>Open this select menu</option>
                                                <option value="Vice-chancellor">Vice-chancellor</option>
                                                <option value="Pro Vice-Chancellor">Pro Vice-Chancellor</option>
                                                <option value="Dean">Dean</option>
                                
                                                <optgroup label="Administrative Offices">
                                                    <option value="Finance Officer">Finance Officer</option>
                                                    <option value="Deputy Registrar">Deputy Registrar</option>
                                                    <option value="Joint Registrar">Joint Registrar</option>
                                                    <option value="Asistant Resigstrar">Asistant Resigstrar</option>

                                                </optgroup>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="control-group">
                                        <label class="control-label"><b>Phone Number(Office)</b> </label>
                                        <div class="controls">
                                            <input type="tel" placeholder="Enter Phone No" name="office" class="span8 tip" maxlength="4" minlength="4" required>
                                        </div>
                                    </div>
                                    <div class="control-group">
                                        <label class="control-label"><b>Phone Number(Home)</b> </label>
                                        <div class="controls">
                                            <input type="tel" placeholder="Enter Phone No" name="home" class="span8 tip" maxlength="4" minlength="4">
                                        </div>
                                    </div>
                                    <div class="control-group">
                                        <label class="control-label"><b>Official Email</b> </label>
                                        <div class="controls">
                                            <input type="email" placeholder="Enter Official Email" autocomplete="off" name="mailid" class="span8 tip" required>
                                        </div>
                                    </div>
                                    <button type="submit" name="submit" class="btn btn-success">Submit</button>
                                </form>
                            </div>
                        </div>
                    </div>
                    <!--/.content-->
                </div>
                <!--/.span9-->
            </div>
        </div>
        <!--/.container-->
    </div>
    <!--/.wrapper-->
</body>

</html>